# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0002_auto_20171019_1108'),
        ('datasets', '0003_auto_20171019_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField(max_length=40)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('specificity', models.FloatField()),
                ('fmeasure', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='datasets.Dataset')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='samples.Sample')),
            ],
        ),
    ]
