# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='ground_truth_binary_image',
            new_name='ground_truth_color_image',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='fmeasure',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='specificity',
        ),
    ]
